### ISSUE TITLE
Support for new reward types in transactions list

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-desktop-wallet#238]
**Task description**
With the addition of new reward types for accounts, we need to be able to show these in the desktop wallet.

**Sub-tasks**
- [ ] Add support for reward types in transaction list
- [ ] Make it possible to filter new reward types
- [ ] Adapt transaction list filter to different account versions
