### ISSUE TITLE
Add transfers with metadata to the desktop wallet

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-desktop-wallet#9]
**Task description**

The node will support adding metadata to transfers, encrypted transfers, and transfers with schedule, and thus the wallet should support it as well.

Metadata that goes into a transaction should be CBOR encoded, but the UI should probably be optimized for the common case where the user inputs a string or an integer value.

**Sub-tasks**
- [ ] Design the UI and flows for adding metadata.
- [ ] Implement sending new transaction types. This should check whether these are enabled on the node already or not, and prevent the user from ideally even constructing these transactions if they are not enabled.
- [ ] Implement displaying metadata for incoming transfers.

Related milestone with details of the changes on the node
- https://github.com/Concordium/concordium-node/milestone/1

**Comment by orhoj** [comment]
@shjortConcordium delivered this with https://github.com/Concordium/concordium-desktop-wallet/pull/44
